export default {
  header: "#FFA07A",
  bottomTab: "#ff7f50",
  white: "white",
  black: "black",
  transparent: "transparent",
  weightRdHeader: "#f5deb3",
  dropdowncolor: "#fafafa",
  placeholder: "#808080",
  shadow: "gray",
  mylocation: "blue",
  dogsParkLoc: "green",
  chartColor: "#f5f5f5",
  profileInfos: "#fffff0",
  modalColor: "#ffc4ad",
  inputPressedColor:"#ccc",
  trackColorFalse: "#767577",
  trackColorTrue: "#81b0ff",
  thumbColorEnabled: "#d4d4d4",
  thumbColorDisabled: "#f4f3f4",
  iosBackgroundColor: "#3e3e3e",
};
